sudo: required
dist: trusty
language: cpp
compiler: gcc
notifications:
  email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - kalakris-cmake
    packages:
    - gcc-5
    - g++-5
    - cmake
before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo add-apt-repository --yes --remove "ppa:kalakris/cmake"
    - sudo apt-get update -qq
    - sudo apt-get install -qq qtbase5-dev qt5-qmake libqt5opengl5-dev libeigen3-dev
install: true
script: mkdir build && cd build && cmake ../ && make -r -j 2
