obj = c-ray-mt.o
bin = c-ray-mt

CC = cc
CFLAGS = -O3 -mips4 -IPA -LNO -TARG:platform=ip30 -Ofast=ip30

$(bin): $(obj)
	$(CC) -o $@ $(obj) -lm -lpthread

.PHONY: clean
clean:
	rm -f $(obj) $(bin)

.PHONY: install
install:
	cp $(bin) /usr/local/bin/$(bin)

.PHONY: uninstall
uninstall:
	rm -f /usr/local/bin/$(bin)
