---
dist: bionic
language:
  - c++
sudo: false
matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env: XCC=gcc-8 XCXX=g++-8
      addons:
        apt:
          packages:
            - g++-8
            - gcc-8
    - compiler: clang
      env: XCC=clang XCXX=clang++
    - env: XCC="gcc-8 -m32" XCXX="g++-8 -m32"
      addons:
        apt:
          packages:
            - g++-8
            - gcc-8
            - g++-8-multilib
            - gcc-8-multilib
            - linux-libc-dev-amd64-cross
            - linux-libc-dev-x32-cross
            - linux-libc-dev-i386-cross
    #- name: aarch64
    #  arch: arm64
    #  env: XCC=gcc XCXX=g++

script:
  - CC="$XCC" CXX="$XCXX" cmake .
  - make -j4 VERBOSE=1
  - make -j4 test ARGS=-V
